const fs = require('fs');
const path = require('path');

/**
 * Reads a cached AI-generated bio from ai-bio-cache.md.
 * This file is generated weekly by .github/workflows/ai-bio.yml
 * which calls the Gemini API with recent GitHub activity.
 */
module.exports = async function () {
  const cachePath = path.join(__dirname, '..', '..', 'ai-bio-cache.md');

  try {
    const bio = fs.readFileSync(cachePath, 'utf-8').trim();
    if (bio) {
      return `<details open>
<summary><strong>🤖 AI-Generated Bio</strong> <em>(rewritten weekly from GitHub activity via Gemini)</em></summary>
<br>

${bio}

<br>
<em><sub>Generated by Google Gemini — this section is rewritten every week based on my recent GitHub activity.</sub></em>
</details>`;
    }
  } catch {
    // Cache file doesn't exist yet (first run or local dev)
  }

  // Fallback when no bio cache exists yet
  return `<!-- ai-bio-cache.md not found — will be generated by the weekly AI bio workflow -->`;
};
