// @ts-check

const fs = require('fs');
const path = require('path');

/**
 * AI-generated bio replacer — reads cached weekly bio from ai-bio-cache.md.
 * @type {import('../types').ReplacerFunction}
 */
module.exports = async function () {
  const cachePath = path.join(__dirname, '..', '..', 'ai-bio-cache.md');

  try {
    const bio = fs.readFileSync(cachePath, 'utf-8').trim();
    if (bio) {
      return `
${bio}

<br>
<em><sub>Generated by Google Gemini — this section is rewritten every week based on my recent GitHub activity.</sub></em>`;
    }
  } catch {
    // Cache file doesn't exist yet (first run or local dev)
  }

  // Fallback when no bio cache exists yet
  return `<!-- ai-bio-cache.md not found — will be generated by the weekly AI bio workflow -->`;
};
