// @ts-check

const fs = require('fs');
const path = require('path');

/**
 * AI-generated bio replacer — reads cached weekly bio from ai-bio-cache.md.
 * @type {import('../types').ReplacerFunction}
 */
module.exports = async function () {
  const cachePath = path.join(__dirname, '..', '..', 'ai-bio-cache.md');

  try {
    const bio = fs.readFileSync(cachePath, 'utf-8').trim();
    if (bio) {
      return `
${bio}

<br>
<em><sub>Generated by Google Gemini — this section is rewritten every week based on my recent GitHub activity.</sub></em>`;
    }
  } catch {
    // Cache file doesn't exist yet (first run or local dev)
  }

  // Fallback when no bio cache exists yet (first run or local dev)
  return `Building AI-powered tools and infrastructure — from agentic coding workflows and multi-agent orchestration systems to LLM-integrated applications. Deep in a NixOS rabbit hole and emerging only to write TypeScript, refactor my Neovim config — again — and occasionally bend Firefox to my will. The profile README you're reading was generated by a fleet of AI agents I orchestrate with OpenCode, which is probably the most meta thing I maintain.`;
};
