/**
 * AI Bio Generator
 *
 * Fetches recent GitHub activity for Thomashighbaugh, sends it to Google Gemini,
 * and writes a fresh bio to ai-bio-cache.md. Designed to run as a GitHub Action
 * on a weekly schedule.
 *
 * Environment variables:
 *   GEMINI_API_KEY  — Google Gemini API key
 *   GITHUB_TOKEN    — GitHub token (for higher API rate limits)
 */

const fs = require('fs');
const path = require('path');

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_USER = 'Thomashighbaugh';

if (!GEMINI_API_KEY) {
  console.error('GEMINI_API_KEY environment variable is required');
  process.exit(1);
}

/**
 * Fetch recent events from the GitHub API.
 */
async function fetchRecentActivity() {
  const headers = { Accept: 'application/vnd.github+json' };
  if (GITHUB_TOKEN) headers.Authorization = `Bearer ${GITHUB_TOKEN}`;

  const res = await fetch(
    `https://api.github.com/users/${GITHUB_USER}/events?per_page=30`,
    { headers },
  );

  if (!res.ok) {
    throw new Error(`GitHub API responded with ${res.status}: ${await res.text()}`);
  }

  const events = await res.json();
  return events.map((e) => ({
    type: e.type,
    repo: e.repo.name,
    created_at: e.created_at,
    payload: e.payload,
  }));
}

/**
 * Fetch repo stats for the user's repos.
 */
async function fetchRepoStats() {
  const headers = { Accept: 'application/vnd.github+json' };
  if (GITHUB_TOKEN) headers.Authorization = `Bearer ${GITHUB_TOKEN}`;

  const res = await fetch(
    `https://api.github.com/users/${GITHUB_USER}/repos?per_page=10&sort=updated&direction=desc`,
    { headers },
  );

  if (!res.ok) {
    throw new Error(`GitHub API responded with ${res.status}: ${await res.text()}`);
  }

  const repos = await res.json();
  return repos.map((r) => ({
    name: r.name,
    description: r.description,
    language: r.language,
    stars: r.stargazers_count,
    forks: r.forks_count,
    updated_at: r.updated_at,
  }));
}

/**
 * Call the Google Gemini API to generate a fresh bio.
 *
 * Uses the free-tier Gemini API via the REST endpoint.
 * Gemini 2.0 Flash (or 1.5 Flash) has the highest free quota.
 */
async function generateBio(activity, repos) {
  const prompt = `You are writing a short, punchy "About Me" bio for a developer's GitHub profile README.

Here is their recent GitHub activity (last 90 days):
${JSON.stringify(activity, null, 2)}

Here are their most recently updated repositories:
${JSON.stringify(repos, null, 2)}

Write a single short paragraph (2-4 sentences) in first person that:
- Sounds like a real human developer, not a robot
- Mentions what they're currently working on based on recent activity
- References their tech stack if evident (NixOS, Neovim, TypeScript, React, Rust, etc.)
- Has personality — not corporate or sterile
- Does NOT start with "I am" or "Hi, I'm"
- Does NOT use emojis
- Is 40-80 words

Example tone:
"Deep in a NixOS rabbit hole and emerging only to write TypeScript. Currently refactoring my dotfiles into a proper Flake while rebuilding my Neovim config — again. The profile README you're reading was generated by a fleet of AI agents I orchestrate with OpenCode, which is probably the most meta thing I maintain."

Now write the bio:`;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.8,
          maxOutputTokens: 200,
          topP: 0.9,
        },
      }),
    },
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Gemini API responded with ${res.status}: ${err}`);
  }

  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error(`Gemini returned no text: ${JSON.stringify(data)}`);
  }

  return text.trim();
}

/**
 * Main execution.
 */
(async function main() {
  try {
    console.log('Fetching recent GitHub activity...');
    const activity = await fetchRecentActivity();

    console.log('Fetching repo stats...');
    const repos = await fetchRepoStats();

    console.log('Generating bio with Gemini...');
    const bio = await generateBio(activity, repos);

    const outputPath = path.join(__dirname, '..', 'ai-bio-cache.md');
    fs.writeFileSync(outputPath, bio + '\n', 'utf-8');
    console.log(`✅ Bio written to ${outputPath}`);
    console.log('--- Generated Bio ---');
    console.log(bio);
    console.log('---');
  } catch (err) {
    console.error('❌ Failed to generate AI bio:', err.message);
    process.exit(1);
  }
})();
