name: Generate README

on:
  workflow_dispatch: # Run workflow via GitHub website
  schedule:
    # Run this workflow everyday at 00:01 UTC
    - cron: '1 0 */1 * *'
  push:
    branches:
      - main

concurrency:
  group: readme-generate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Thomashighbaugh
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --prod --no-frozen-lockfile

      - name: Generate README
        run: node src/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        working-directory: Thomashighbaugh
        run: |-
          git diff
          git config --global user.email "readme-bot@github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "docs: regenerate profile README ($(date +%Y-%m-%d))" || exit 0
          git push
